import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the AI SDLC course (docs instance id `ai-sdlc`, served at
 * `/ai-sdlc`). Autogenerated from the `docs-ai-sdlc/` folder, exactly like the
 * RAG course's sidebar: the Intro, Parts I–V and the Glossary appear from the
 * folder structure alone (`sidebar_position` frontmatter + `_category_.json`
 * order), so adding or reordering a lesson needs no edit here. Whether a Part
 * heading navigates or merely expands is likewise decided in the content tree, by
 * the `link` key in that Part's `_category_.json` — not here.
 */
const sidebars: SidebarsConfig = {
  aiSdlcSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
