import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the Design Scenarios course (docs instance id `design-scenarios`,
 * served at `/design-scenarios`). Autogenerated from the `docs-design-scenarios/`
 * folder, exactly like the other two courses: the Intro and the scenario tracks
 * appear from the folder structure alone (`sidebar_position` frontmatter +
 * `_category_.json` order), so adding a scenario needs no edit here.
 */
const sidebars: SidebarsConfig = {
  designScenariosSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
